-- 테스트 환경에서 사용하기 위한 더미 데이터를 삽입하기 위해 test/resources 디렉터리 내부에 배치함
INSERT INTO CASH_CARD(ID, AMOUNT) VALUES (99, 123.45);
INSERT INTO CASH_CARD(ID, AMOUNT) VALUES (100, 1.00);
INSERT INTO CASH_CARD(ID, AMOUNT) VALUES (101, 150.00);