-- 실제 프로덕션 환경과 테스트 환경에서 데이터베이스 스키마는 항상 동일하므로 main/resources 디렉터리 내부에 배치함
CREATE TABLE cash_card
(
    ID     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AMOUNT NUMBER NOT NULL DEFAULT 0
);